#OUTDATED!!!
# 1/30/2015
# Comparing Mean matrices generated from ASE to that generated by element-wise mean of the Adj Matrix
setwd("~/Simplex/SimplexMDK/Code")
library("igraph")
library("vioplot")
library("rARPACK")
source("generateSBM_Z.R")
source("generateZ_nxk.R")
source("spectEmbed.R")


# Parameters
B <- matrix(c(.42, .42, .42,.5),2);
PI <- c( .5, .5);
n <- 10;
m <- 1;
trials <- 1000;
max_k <- 5;
myoptions <- igraph.arpack.default
myoptions$maxiter <- 20000


# Run
k <- length(PI)
error_Phat <- matrix(0, trials, max_k);
error_mean <- matrix(0, trials, 1);
for (i in 1:trials) {
  Z_nxk <- generateZ_nxk(PI, n);
  P_Bar <- matrix(0,n,n);
  for (h in 1:m) {
    g <- generateSBM_Z(B, Z_nxk)
    P_Bar <- P_Bar +g$A
  }
  P_Bar <- P_Bar/m;
  err_v <- g$P-P_Bar;
  err_v <- err_v[upper.tri(err_v)];
  error_mean[i,1] <- mean(err_v^2);
  for (j in 1:max_k) {
    repeat{
      g$ASE <- try(spectEmbed(P_Bar,j, myoptions))
      if (class(g$ASE) != "try-error") {
        break
      }
      print("err")
    }
    P_hat = g$ASE$X %*% t(g$ASE$X);
    err_v <- g$P-P_hat;
    err_v <- err_v[upper.tri(err_v)];
    error_Phat[i,j] <- mean(err_v^2);;
  }
}

#vioplot( error_mean, error_Phat[,1], error_Phat[,2],error_Phat[,3], error_Phat[,4], error_Phat[,5],  error_Phat[,6], error_Phat[,7], error_Phat[,8], error_Phat[,9], names = c("Naive Mean", "k=1","k=2", "k=3", "k=4", "k=5", "k=6","k=7","k=8","k=9"));
#vioplot( error_mean, error_Phat[,1], error_Phat[,2],error_Phat[,3], error_Phat[,4], error_Phat[,5],  error_Phat[,6], error_Phat[,7], error_Phat[,8], error_Phat[,9], error_Phat[,10], error_Phat[,11], error_Phat[,12],error_Phat[,13], error_Phat[,14], error_Phat[,15],  error_Phat[,16], error_Phat[,17], error_Phat[,18], error_Phat[,19], names = c("Naive Mean", "k=1", "k=2", "k=3", "k=4", "k=5", "k=6","k=7","k=8","k=9", "k=10", "k=11", "k=12", "k=13", "k=14", "k=15", "k=16","k=17","k=18","k=19"));
vioplot( error_mean, error_Phat[,1], error_Phat[,2],error_Phat[,3], error_Phat[,4], error_Phat[,5], names = c("Naive Mean", "k = 1", "k = 2", "k = 3", "k = 4", "k = 5"));
title("M = 100, N = 100")
