# 1/30/2015
# Model: Dirilecht Generalized SBM 
# Comparing Mean matrices generated from ASE to that generated by element-wise mean of the Adj Matrix
rm(list = ls())
setwd("~/Simplex/SimplexMDK/Code/EF_NMF_PlotFunc/")
library("igraph")
library("vioplot")
library("rARPACK")
library("mclust")
library("nloptr")
library("fields")
library("doParallel")
library("foreach")
source("../graphFunctions.R")
source("../generateDirilechtSBM.R");

mcl = makeCluster(3);
registerDoParallel(mcl);
MN_M = matrix(c(100, 20, 100,60, 100,80,100,100,100,260,100, 500,100,1000),7,2,byrow=TRUE)
MN_N = matrix(c(1,100,10,100,50,100,100, 100,500,100,1000,100,2000,100, 5000,100),8,2,byrow=TRUE)
#MN = matrix(c(1,100,100,100),4,2,byrow=TRUE)
#B <- matrix(c(.22, .22, .22,.6),2);
#B <- matrix(c(.42, .42, .42,.5),2);
B2_1 <- matrix(c(.42, .2, .2, .7),2);
B2_2 <- matrix(c(.1, .02, .02, .07),2);
B2_3 <- matrix(c(.9, .2, .2, .8),2);
B2_4 <- matrix(c(.5, .4, .4, .6),2);
B2_5 <- matrix(c(.02, .005, .005, .03),2);
B_Assign = matrix(c(1, 0, 2, 3),2);
B3 <- matrix(c(.42, .2, .3, .2,.5, .15, .3, .15, .7),3);
#B3 <- matrix(c(.42, .23, .35, .23,.5, .15, .35, .15, .7),3);
B4 <- matrix(c(.42, .2, .3 ,.05, .2, .49, .35, .15, .3, .35, .6, .25, .05 , .15,.25, .7),4);
Bs = list(B2_1,B2_1,B2_1,B2_1)
PI4 <- c( .25, .25, .25, .25);
PI3 <- c(.33, .33,.34)
PI2_1 <- c(.5,.5);
PI2_2 <- c(.25,.75);
PI2_3 <- c(.1,.9);
PI2_4 <- c(.05,.95);
PI2_5 <- c(.01,.99);
PIs = list(PI2_1,PI2_2,PI2_3,PI2_4)
trials <- 1000;
max_j <- 6;

myoptions <- igraph.arpack.default
myoptions$maxiter <- 20000

bias_M_Naive = matrix(0,length(PIs),dim(MN_M)[1]);
bias_M_ASE = rep(list(matrix(0,length(PIs),dim(MN_M)[1])),max_j);

err_byBlock = rep(list(rep(list(matrix(0,3,dim(MN_M)[1])),max_j)),length(PIs))
err_Naive_byBlock = rep(list(matrix(0,3,dim(MN_M)[1])),length(PIs))
eff_byBlock = rep(list(rep(list(matrix(0,3,dim(MN_M)[1])),max_j)),length(PIs))
var_eff_byBlock = rep(list(rep(list(matrix(0,3,dim(MN_M)[1])),max_j)),length(PIs))
var_err_byBlock = rep(list(rep(list(matrix(0,3,dim(MN_M)[1])),max_j)),length(PIs))

for (ind in 1:length(PIs)){
  for (run in 1:dim(MN_M)[1]) {
    print(c(ind, run))
    PI = PIs[[ind]];
    B = Bs[[ind]]
    n <- MN_M[run,2];
    m <- MN_M[run,1];
    error_Phat_noClust <- matrix(0, trials, max_j);
    error_mean <- matrix(0, trials, 1);
    bias_Naive <- matrix(0, trials, 1);
    bias_ASE <- matrix(0, trials, max_j);
    err_block <- rep(list(matrix(0,trials,3)),max_j)
    eff_block <- rep(list(matrix(0,trials,3)),max_j)
    err_Naive_block <- matrix(0,trials,3)
    for (i in 1:trials) {
      if (i%%100 ==0)
        print(i)
      Z <-generateZ_nxk_exact(PI,n)
      P = Z %*% B %*% t(Z);
      P_Assign = Z %*% B_Assign %*% t(Z);
      P_Bar = makeP_Bar(P,m,n)
      
      err_v <- P-P_Bar;
      err_v <- err_v[upper.tri(err_v)];
      error_mean[i,1] <- mean(err_v^2);
      bias_Naive[i,1] <- mean(err_v);
      #j = 2;
      #error_mean[i,1] <- norm(err_v, type="2");
      diag(P_Bar) <- diag(P);
      for (j in 1:max_j) {
        repeat{
          ASE <- try(spectEmbed(P_Bar,j, DAdjust=FALSE, opt = myoptions))
          if (class(ASE) != "try-error") {
            break
          }
          print("err")
        }
        P_hat_noClust <- ASE$X %*% t(ASE$X);
        err_v_noClust <- P-P_hat_noClust;
        err_v_noClust <- err_v_noClust[upper.tri(err_v_noClust)];
        error_Phat_noClust[i,j] <- mean(err_v_noClust^2);
        bias_ASE[i,j] = mean(err_v_noClust);
        err_Assign = P_Assign[upper.tri(P_Assign)];
        for (k in 1:3) {
          err_block[[j]][i, k] = mean((err_v_noClust[(err_Assign==k)])^2);
          err_Naive_block[i,k] = mean((err_v[(err_Assign==k)])^2);
          eff_block[[j]][i, k] = mean((err_v_noClust[(err_Assign==k)])^2)/mean((err_v[(err_Assign==k)])^2)
        }
      
      }
    }
    #     print(mean(error_mean));
    #     print(mean(error_Phat_noClust[,j]))
    #     print(mean(error_Phat[,j]))

    bias_M_Naive[ind,run] = mean(bias_Naive)
    
    for (j in 1:max_j){
      bias_M_ASE[[j]][ind,run] = mean(bias_ASE[,j])
    }
    for (k in 1:3){
      err_Naive_byBlock[[ind]][k,run] = mean(err_Naive_block[,k],na.rm = TRUE)
      for (j in 1:max_j) {
        err_byBlock[[ind]][[j]][k,run] = mean(err_block[[j]][,k],na.rm = TRUE)
        eff_byBlock[[ind]][[j]][k,run] = mean(eff_block[[j]][,k],na.rm = TRUE)
        var_eff_byBlock[[ind]][[j]][k,run] = var(eff_block[[j]][,k],na.rm = TRUE)
        var_err_byBlock[[ind]][[j]][k,run] =  var(err_block[[j]][,k],na.rm = TRUE)
      }
    }
  }
}


# par(mfrow=c(1,2));
# N_mat = matrix(rep(MN_M[,2],6), ncol =6)
# invN = (1/(MN_M[,2]))
# matplot( N_mat,cbind(inv2N,t(eff_M)),type = "b", xlab= "N", ylab = "RE", pch = 19, lwd = 2,col = c("black", "red", "green", "blue", "orange", "cyan"))
# title("Relative Efficiency with M =100")
# legend(locator(1), , legend = c("2/N", expression('p'[1]*' = .5'), expression('p'[1]*' = .25'), expression('p'[1]*' = .1'), expression('p'[1]*' = .05'), expression('p'[1]*' = .01')), lty = c(19,19,19,19), col = c("black", "red", "green", "blue", "orange", "cyan"), lwd = 2)
# 
# matplot( N_mat[,1:5],t(eff_M)/matrix(rep(inv2N,5), ncol =5),type = "b", xlab= "N", ylab = "RE*N/2", pch = 19, lwd = 2, col = c("red", "green", "blue", "orange", "cyan","purple"))
# legend(locator(1), legend = c(expression('p'[1]*' = .5'), expression('p'[1]*' = .25'), expression('p'[1]*' = .1'), expression('p'[1]*' = .05'), expression('p'[1]*' = .01')), lty = c(19,19,19), col = c("red", "green", "blue", "orange", "cyan"), lwd = 2)
# title("Relative Efficiency*N/2, k = 2")


par(mfrow=c(1,2));
N_mat = matrix(rep(MN_M[,2],4), ncol =4)
invN = (1/(MN_M[,2]))
matplot( N_mat,cbind(inv1N,t(eff_byBlock[[1]][[3]])),type = "b", xlab= "N", ylab = "RE", pch = 19, lwd = 2,col = c("black", "red", "green", "blue", "orange", "cyan"))
title("Relative Efficiency with M =100")
legend(locator(1), , legend = c("2/N",  "p = .42", "p = .2", "p = .7"), lty = c(19,19,19,19), col = c("black", "red", "green", "blue", "orange", "cyan"), lwd = 2)

matplot( N_mat[,1:3],t(eff_byBlock[[1]][[3]])/matrix(rep(invN,3), ncol =3),type = "b", xlab= "N", ylab = "RE*N/2", pch = 19, lwd = 2, col = c("red", "green", "blue", "orange", "cyan","purple"))
legend(locator(1), legend = c("p = .42", "p = .2", "p = .7"), lty = c(19,19,19), col = c("red", "green", "blue", "orange", "cyan"), lwd = 2)
title("Relative Efficiency*N/2, k = 2")
