# 1/30/2015
# Model: Dirilecht Generalized SBM 
# Comparing Mean matrices generated from ASE to that generated by element-wise mean of the Adj Matrix
setwd("~/Simplex/SimplexMDK/Code/EF_NMF_PlotFunc/")
library("igraph")
library("vioplot")
library("rARPACK")
library("mclust")
library("nloptr")
library("fields")
library("doParallel")
library("foreach")
source("../graphFunctions.R")
source("../generateDirilechtSBM.R");

mcl = makeCluster(3);
registerDoParallel(mcl);
MN_M = matrix(c(100,10, 100, 25, 100,50, 100,75,100,100,100,250,100, 500),7,2,byrow=TRUE)
MN_N = matrix(c(1,100,10,100,50,100,100, 100,500,100,1000,100,2000,100, 5000,100),8,2,byrow=TRUE)
#MN = matrix(c(1,100,100,100),4,2,byrow=TRUE)
#B <- matrix(c(.22, .22, .22,.6),2);
#B <- matrix(c(.42, .42, .42,.5),2);
B2 <- matrix(c(.42, .2, .2, .7),2);

B3 <- matrix(c(.42, .2, .3, .2,.5, .15, .3, .15, .7),3);
#B3 <- matrix(c(.42, .23, .35, .23,.5, .15, .35, .15, .7),3);
B4 <- matrix(c(.42, .2, .3 ,.05, .2, .49, .35, .15, .3, .35, .6, .25, .05 , .15,.25, .7),4);
Bs = list(B2,B3,B4)
PI4 <- c( .25, .25, .25, .25);
PI3 <- c(.33, .33,.34)
PI2 <- c(.5,.5);
PIs = list(PI2,PI3,PI4)
trials <- 1000;
max_k <- 4;
nclust <- 3;
myoptions <- igraph.arpack.default
myoptions$maxiter <- 20000
eff_M = matrix(0,6,7);
eff_N = matrix(0,6,7);
eff_M_S = matrix(0,6,7);
eff_N_S = matrix(0,6,7);
eff_M_var = matrix(0,6,7);
eff_N_var = matrix(0,6,7);
bias_M_Naive = matrix(0,6,7);
bias_M_ASE = matrix(0,6,7);
for (ind in 1:1){
  for (run in 1:7) {
    PI = PIs[[3]];
    B = Bs[[3]]
    n <- MN_M[run,2];
    m <- MN_M[run,1];
    error_Phat_noClust <- matrix(0, trials, 6);
    error_Phat <- matrix(0, trials, max_k);
    error_mean <- matrix(0, trials, 1);
    bias_Naive <- matrix(0, trials, 1);
    bias_ASE <- matrix(0, trials, 6);
    eff_M_bySample <- matrix(0, trials, 6);
    for (i in 1:trials) {
      if (i%%100 ==0)
        print(i)
      Z <-generateZ_nxk(PI,n)
      P = Z %*% B %*% t(Z);
      P_Bar <- matrix(0,n,n);
      
      if (m < 500 && n < 50){
        for (h in 1:m) {
          g <- P2Adj(P);
          P_Bar <- P_Bar +g;
        }
      } else {
        P_Bar <- foreach(mb = breakScalar(m, 3)) %dopar%{
          Ps_i = matrix(0,n,n);
          for (h in 1:mb) {
            g <- P2Adj(P);
            Ps_i <- Ps_i +g;
          }
          return(Ps_i)
        }
        P_Bar <- Reduce('+',P_Bar);
      }
      P_Bar <- P_Bar/m;
      
      err_v <- P-P_Bar;
      err_v <- err_v[upper.tri(err_v)];
      error_mean[i,1] <- mean(err_v^2);
      bias_Naive[i,1] <- mean(err_v);
      j = ind+1;
      #error_mean[i,1] <- norm(err_v, type="2");
      diag(P_Bar) <- diag(P);
      for (j in 1:6) {
      repeat{
        ASE <- try(spectEmbed(P_Bar,j, DAdjust=FALSE, opt = myoptions))
        if (class(ASE) != "try-error") {
          break
        }
        print("err")
      }
      P_hat_noClust <- ASE$X %*% t(ASE$X);
      err_v_noClust <- P-P_hat_noClust;
      err_v_noClust <- err_v_noClust[upper.tri(err_v_noClust)];
      error_Phat_noClust[i,j] <- mean(err_v_noClust^2);
      bias_ASE[i,j] = mean(err_v_noClust);
      eff_M_bySample[i,j] <- mean(err_v_noClust^2)/error_mean[i,1];
      
      
      }
    }
#     print(mean(error_mean));
#     print(mean(error_Phat_noClust[,j]))
#     print(mean(error_Phat[,j]))
    for (j in 1:6){
    bias_M_ASE[j,run] = mean(bias_ASE);
    bias_M_Naive[j,run] = mean(bias_Naive);
    eff_M_S[j,run] = mean(eff_M_bySample[,j])
    eff_M_var[j,run] = var(eff_M_bySample[,j])
    eff_M[j,run] = mean(error_Phat_noClust[,j])/mean(error_mean)
    }
  }
}

# for (ind in 1:3){
#   for (run in 1:8) {
#     PI = PIs[[ind]];
#     B = Bs[[ind]]
#     n <- MN_N[run,2];
#     m <- MN_N[run,1];
#     error_Phat_noClust <- matrix(0, trials, max_k);
#     error_Phat <- matrix(0, trials, max_k);
#     error_mean <- matrix(0, trials, 1);
#     eff_N_bySample <- matrix(0, trials, 1);
#     for (i in 1:trials) {
#       if (i%%100 ==0)
#         print(i)
#       Z <-generateZ_nxk(PI,n)
#       P = Z %*% B %*% t(Z);
#       P_Bar <- matrix(0,n,n);
#       
#       if (m < 500 && n < 50){
#         for (h in 1:m) {
#           g <- P2Adj(P);
#           P_Bar <- P_Bar +g;
#         }
#       } else {
#         P_Bar <- foreach(mb = breakScalar(m, 3)) %dopar%{
#           Ps_i = matrix(0,n,n);
#           for (h in 1:mb) {
#             g <- P2Adj(P);
#             Ps_i <- Ps_i +g;
#           }
#           return(Ps_i)
#         }
#         P_Bar <- Reduce('+',P_Bar);
#       }
#       P_Bar <- P_Bar/m;
#       
#       err_v <- P-P_Bar;
#       err_v <- err_v[upper.tri(err_v)];
#       error_mean[i,1] <- mean(err_v^2);
#       j = ind+1;
#       #error_mean[i,1] <- norm(err_v, type="2");
#       diag(P_Bar) <- diag(P);
#       #for (j in 1:max_k) {
#       repeat{
#         ASE <- try(spectEmbed(P_Bar,j, DAdjust=FALSE, opt = myoptions))
#         if (class(ASE) != "try-error") {
#           break
#         }
#         print("err")
#       }
#       P_hat_noClust <- ASE$X %*% t(ASE$X);
#       err_v_noClust <- P-P_hat_noClust;
#       err_v_noClust <- err_v_noClust[upper.tri(err_v_noClust)];
#       error_Phat_noClust[i,j] <- mean(err_v_noClust^2);
#       eff_N_bySample[i,1] <- mean(err_v_noClust^2)/error_mean[i,1];
#       
#       
#       #}
#     }
#     print(mean(error_mean));
#     print(mean(error_Phat_noClust[,j]))
#     print(mean(error_Phat[,j]))
#     eff_N_S[ind,run] = mean(eff_M_bySample)
#     eff_N_var[ind,run] = var(eff_M_bySample)
#     eff_N[ind,run] = mean(error_Phat_noClust[,j])/mean(error_mean)
#   }
# }

# d_M = data.frame(
#   N = MN_M[,2])
# ,ASE_M = eff_M
# ,NMF_M = eff_NMF_M
# ) 
# 

# par(mfrow=c(1,1));
# N_mat = matrix(rep(MN_M[,2],4), ncol =4)
# inv2N = (2/(MN_M[,2]))
# matplot( N_mat,cbind(inv2N,t(eff_M)),type = "b", xlab= "N", ylab = "RE", pch = 19, lwd = 2,col = c("black", "red", "green", "blue"))
# title("Relative Efficiency with M =100")
# legend(locator(1), , legend = c("2/N", "k, d = 2", "k, d = 3", "k, d = 4"), lty = c(19,19,19,19), col = c("black", "red", "green", "blue"), lwd = 2)
# 
# 
# par(mfrow=c(1,1));
# matplot( N_mat[,1:3],t(eff_M)/matrix(rep(inv2N,3), ncol =3),type = "b", xlab= "N", ylab = "RE*N/2", pch = 19, lwd = 2, col = c("red", "green", "blue", "orange", "cyan","purple"))
# legend(locator(1), c( "k, d = 2", "k, d = 3", "k, d = 4"), lty = c(19,19,19), col = c("red", "green", "blue", "orange", "cyan","purple"), lwd = 2)
# title("Relative Efficiency*N/2")
# 








 par(mfrow=c(1,2));
 N_mat = matrix(rep(MN_M[,2],7), ncol =7)
 inv2N = (2/(MN_M[,2]))
matplot( N_mat,cbind(inv2N,t(eff_M)),type = "b", xlab= "N", ylab = "RE", pch = 19, lwd = 2,col = c("black", "red", "green", "blue", "orange", "cyan","purple"))
title("Relative Efficiency with M =100, k = 4")
legend(locator(1), , legend = c("2/N","d = 1", "d = 2", "d = 3", "d = 4", "d = 5", "d = 6"), lty = c(19,19,19,19,19,19), col = c("black", "red", "green", "blue", "orange", "cyan","purple"), lwd = 2)

matplot( N_mat[,1:4],cbind(inv2N,t(eff_M[4:6,])),type = "b", xlab= "N", ylab = "RE", pch = 19, lwd = 2,col = c("black", "orange", "cyan","purple"))
title("Relative Efficiency with M =100, k = 4")
legend(locator(1), c("2/N", "d = 4", "d = 5", "d = 6"), lty = c(19,19,19,19,19,19), col = c("black", "orange", "cyan","purple"), lwd = 2)

# 
# par(mfrow=c(1,2));
# matplot( N_mat[,1:6],t(eff_M)/matrix(rep(inv2N,6), ncol =6),type = "b", xlab= "N", ylab = "RE*N/2", pch = 19, lwd = 2, col = c("red", "green", "blue", "orange", "cyan","purple"))
# legend(locator(1), c("d = 1", "d = 2", "d = 3", "d = 4", "d = 5", "d = 6"), lty = c(19,19,19), col = c("red", "green", "blue", "orange", "cyan","purple"), lwd = 2)
# title("Relative Efficiency*N/2, k = 4")
# 
# matplot( N_mat[,1:3],t(eff_M[4:6,])/matrix(rep(inv2N,3), ncol =3),type = "b", xlab= "N", ylab = "RE*N/2", pch = 19, lwd = 2, col = c( "orange", "cyan","purple"))
# legend(locator(1), c( "d = 4", "d = 5", "d = 6"), lty = c(19,19,19), col = c( "orange", "cyan","purple"), lwd = 2)
# title("Relative Efficiency*N/2, k = 4")

M_mat = matrix(rep(MN_N[,1],3), ncol =3)
matplot( M_mat,t(eff_N),type = "b", xlab= "M", ylab = "RE", pch = 19, lwd = 2,col = c("red", "green", "blue"))
title("Relative Efficiency with N =100")
legend(locator(1), c("k, d = 2", "k, d = 3", "k, d = 4"), lty = c(19,19,19), col = c("red", "green", "blue"), lwd = 2)

matplot( M_mat[1:5,],t(eff_N)[1:5,],type = "b", xlab= "M", ylab = "RE", pch = 19, lwd = 2,col = c("red", "green", "blue"))
title("Relative Efficiency with N =100")
legend(locator(1), c("k, d = 2", "k, d = 3", "k, d = 4"), lty = c(19,19,19), col = c("red", "green", "blue"), lwd = 2)
