# 1/30/2015
# Model: Dirilecht Generalized SBM 
# Comparing Mean matrices generated from ASE to that generated by element-wise mean of the Adj Matrix
setwd("~/Simplex/SimplexMDK/Code/EF_NMF_PlotFunc/")
library("igraph")
library("NMF")
library("rARPACK")
library("mclust")
library("nloptr")
library("fields")
source("../graphFunctions.R")
source("../generateDirilechtSBM.R");
library("doParallel")
library("foreach")

mcl = makeCluster(3);
registerDoParallel(mcl);
MN_M = matrix(c(5,5,5,10, 5, 25, 5,50, 5,75, 5,100),6,2,byrow=TRUE)
MN_N = matrix(c(1,100,5,100,10,100, 25, 100,50,100,100,100),6,2,byrow=TRUE)
MN_M1 = matrix(c(1,5,1,10, 1, 25, 1,50, 1,75, 1,100),6,2,byrow=TRUE)
#MN = matrix(c(1,100,100,100),4,2,byrow=TRUE)
#B <- matrix(c(.22, .22, .22,.6),2);
#B <- matrix(c(.42, .42, .42,.5),2);
B2_1 <- matrix(c(.42, .2, .2, .7),2);
B2_2 <- matrix(c(.042, .02, .02, .07),2);
B2_3 <- matrix(c(.02, .005, .005, .03),2);
B3_1 <- matrix(c(.42, .2, .3, .2,.5, .15, .3, .15, .7),3);
B3_2 <- matrix(c(.042, .02, .03, .02,.05, .015, .03, .015, .07),3);
#B3 <- matrix(c(.42, .23, .35, .23,.5, .15, .35, .15, .7),3);
B4_1 <- matrix(c(.42, .2, .3 ,.05, .2, .49, .35, .15, .3, .35, .6, .25, .05 , .15,.25, .7),4);
B4_2 <- matrix(c(.042, .02, .03 ,.005, .02, .049, .035, .015, .03, .035, .06, .025, .005 , .015,.025, .07),4);
Bs = list(B2_1,B3_1,B4_1)
#Bs = list(B2_1,B3_1,B4_1)
PI4 <- c( .25, .25, .25, .25);
PI3 <- c(.33, .33,.34)
PI2 <- c(.5,.5);
PIs = list(PI2, PI3, PI4)
trials <- 1000;
max_k <- 4;
nclust <- 3;
myoptions <- igraph.arpack.default
myoptions$maxiter <- 20000
eff_M_NMF = matrix(0,length(PIs),dim(MN_N)[1]);
eff_M = matrix(0,length(PIs),dim(MN_N)[1]);
eff_M_S_NMF = matrix(0,length(PIs),dim(MN_N)[1]);
eff_M_S = matrix(0,length(PIs),dim(MN_N)[1]);
eff_M_var_NMF = matrix(0,length(PIs),dim(MN_N)[1]);
eff_M_var = matrix(0,length(PIs),dim(MN_N)[1]);
err_M = matrix(0,length(PIs),dim(MN_N)[1])
err_M_NMF = matrix(0,length(PIs),dim(MN_N)[1])
t_NMF = matrix(0,length(PIs),dim(MN_N)[1]);
t_ASE = matrix(0,length(PIs),dim(MN_N)[1]);
for (ind in 1:length(PIs)){
  for (run in 1:dim(MN_N)[1]) {
    print(c(ind, run))
    PI = PIs[[ind]];
    B = Bs[[ind]]
    n <- MN_N[run,2];
    m <- MN_N[run,1];
    error_Phat_noClust <- matrix(0, trials, max_k);
    error_Phat <- matrix(0, trials, max_k);
    error_mean <- matrix(0, trials, 1);
    eff_M_bySample <- matrix(0, trials, 1);
    for (i in 1:trials) {
      if (i%%100 ==0)
        print(i)
      Z <-generateZ_nxk(PI,n)
      P = Z %*% B %*% t(Z);
      P_Bar <- makeP_Bar(P,m,n)
      
      empty <- rowSums(P_Bar) == 0;
      if (sum(empty)>.2*n){
        i = i-1;
        print(i)
        next
      }
      P_Bar <- P_Bar[!empty,!empty];
      P <- P[!empty,!empty]
      #diag(P_Bar) <- rowSums(P_Bar)/(dim(P_Bar)[1]-1);
      err_v <- P-P_Bar;
      err_v <- err_v[upper.tri(err_v)];
      error_mean[i,1] <- mean(err_v^2);
      j = dim(B)[1];
      #error_mean[i,1] <- norm(err_v, type="2");
      #diag(P_Bar) <- diag(P);
      #diag(P_Bar) <- rowSums(P_Bar)/(dim(P_Bar)[1]-1);
      ptm <- proc.time();
      ASE <- nmf(P_Bar,2, '.M#brunet', seed  = "nndsvd")
      t_NMF[ind,run] <- t_NMF[ind,run] +(proc.time()-ptm);
      P_hat_noClust <- basis(ASE) %*% coef(ASE);
      err_v_noClust <- P-P_hat_noClust;
      err_v_noClust <- err_v_noClust[upper.tri(err_v_noClust)];
      error_Phat_noClust[i,j] <- mean(err_v_noClust^2);
      eff_M_bySample[i,1] <- mean(err_v_noClust^2)/error_mean[i,1];
      
      
      #}
    }
    print(mean(error_mean));
    print(mean(error_Phat_noClust[,j]))
    print(mean(error_Phat[,j]))
    eff_M_S_NMF[ind,run] = mean(eff_M_bySample)
    eff_M_var_NMF[ind,run] = var(eff_M_bySample)
    eff_M_NMF[ind,run] = mean(error_Phat_noClust[,j])/mean(error_mean)
    err_M_NMF[ind,run] = mean(error_Phat_noClust[,j]);
  }
}

for (ind in 1:length(PIs)){
  for (run in 1:dim(MN_N)[1]) {
    print(c(ind, run))
    PI = PIs[[ind]];
    B = Bs[[ind]]
    n <- MN_N[run,2];
    m <- MN_N[run,1];
    error_Phat_noClust <- matrix(0, trials, max_k);
    error_Phat <- matrix(0, trials, max_k);
    error_mean <- matrix(0, trials, 1);
    eff_M_bySample <- matrix(0, trials, 1);
    for (i in 1:trials) {
      if (i%%100 ==0)
        print(i)
      Z <-generateZ_nxk(PI,n)
      P = Z %*% B %*% t(Z);
      P_Bar <- makeP_Bar(P,m,n)
      
      empty <- rowSums(P_Bar) == 0;
      if (sum(empty)>.2*n){
        i = i-1;
        print(i)
        next
      }
      P_Bar <- P_Bar[!empty,!empty];
      P <- P[!empty,!empty]
      
      err_v <- P-P_Bar;
      err_v <- err_v[upper.tri(err_v)];
      error_mean[i,1] <- mean(err_v^2);
      j = dim(B)[1];
      #error_mean[i,1] <- norm(err_v, type="2");
      #diag(P_Bar) <- diag(P);
      #diag(P_Bar) <- rowSums(P_Bar)/(dim(P_Bar)[1]-1);
      #for (j in 1:max_k) {
#       repeat{
#         ASE <- try(spectEmbed(P_Bar,j, DAdjust=FALSE, opt = myoptions))
#         if (class(ASE) != "try-error") {
#           break
#         }
#         print("err")
#       }
      ptm <- proc.time();
      ASE <- Schein(P_Bar,j, 3, opt = myoptions)
      t_ASE[ind,run] <- t_ASE[ind,run] +(proc.time()-ptm);
      P_hat_noClust <- ASE$X %*% t(ASE$X);
      err_v_noClust <- P-P_hat_noClust;
      err_v_noClust <- err_v_noClust[upper.tri(err_v_noClust)];
      error_Phat_noClust[i,j] <- mean(err_v_noClust^2);
      eff_M_bySample[i,1] <- mean(err_v_noClust^2)/error_mean[i,1];
      
      
      #}
    }
    print(mean(error_mean));
    print(mean(error_Phat_noClust[,j]))
    print(mean(error_Phat[,j]))
    eff_M_S[ind,run] = mean(eff_M_bySample)
    eff_M_var[ind,run] = var(eff_M_bySample)
    eff_M[ind,run] = mean(error_Phat_noClust[,j])/mean(error_mean)
    err_M[ind,run] = mean(error_Phat_noClust[,j]);
  }
}


#save.image(file = "NMFPlot_Farin.RData")

# par(mfrow=c(1,2));
# M_mat = matrix(rep(MN_N[,1],6), ncol =6)
# inv2N = (2/(MN_N[,2]))
# matplot( M_mat[1:6,],cbind(t(eff_M[,1:6]), t(eff_M_NMF[,1:6])),type = "b", lty = c(1,1,1,2,2,2),  xlab= "M", ylab = "RE", pch = 19, lwd = 2,col = c("red", "green", "blue"))
# title("Relative Efficiency with N =100")
# legend(locator(1), c("ASE k, d = 2", "ASE k, d = 3", " ASE k, d = 4", "NMF k, d = 2", "NMF k, d = 3", " NMF k, d = 4"), lty = c(1,1,1,2,2,2), col = c("red", "green", "blue"), lwd = 2)
# 
# 
# matplot( M_mat,cbind(t(eff_M[,1:6]), t(eff_M_NMF[,1:6]))/matrix(rep(inv2N,6), ncol =6),type = "b", xlab= "N", ylab = "RE*N/2",lty = c(1,1,1,2,2,2), pch = 19, lwd = 2, col = c("red", "green", "blue"))
# legend(locator(1), c("k, d = 2", "k, d = 3", "k, d = 4"), lty = c(19,19,19), col = c("red", "green", "blue"), lwd = 2)
# title("Relative Efficiency*N/2, k = 3")
