# 1/30/2015
# Model: Dirilecht Generalized SBM 
# Comparing Mean matrices generated from ASE to that generated by element-wise mean of the Adj Matrix
setwd("~/Simplex/SimplexMDK/Code")
library("igraph")
library("vioplot")
library("rARPACK")
library("nloptr")
source("graphFunctions.R")
source("generateDirilechtSBM.R");


B <- matrix(c(.42, .42, .42,.5),2);
PI <- c( .5, .5);
n <- 10;
m <- 1;
trials <- 1000;
max_k <- 5;
r <- 20;
myoptions <- igraph.arpack.default
myoptions$maxiter <- 20000

error_Phat <- matrix(0, trials, max_k);
error_mean <- matrix(0, trials, 1);
BASE <- generateDirilechtBASE(B, myoptions)
for (i in 1:trials) {
  d_graph <- generateDirilechtSBM_BASE( BASE, PI, n, r);
  P <- d_graph$P;
  P_Bar <- matrix(0,n,n);
  for (h in 1:m) {
    g <- P2Adj(P);
    P_Bar <- P_Bar +g;
  }
  P_Bar <- P_Bar/m;
  err_v <- P-P_Bar;
  err_v <- err_v[upper.tri(err_v)];
  error_mean[i,1] <- mean(err_v^2);
  for (j in 1:max_k) {
    repeat{
      ASE <- try(spectEmbed(P_Bar,j, myoptions))
      if (class(ASE) != "try-error") {
        break
      }
      print("err")
    }
    P_hat <- ASE$X %*% t(ASE$X);
    err_v <- P-P_hat;
    err_v <- err_v[upper.tri(err_v)];
    error_Phat[i,j] <- mean(err_v^2);;
  }
}

vioplot( error_mean, error_Phat[,1], error_Phat[,2],error_Phat[,3], error_Phat[,4], error_Phat[,5], names = c("Naive Mean", "k = 1", "k = 2", "k = 3", "k = 4", "k = 5"));
#vioplot( ASE$X[,1], ASE$X[,2],ASE$X[,3], ASE$X[,4], ASE$X[,5], names = c( "1", "2", "3", "4", "5"));
title("M = 100, N = 10, r = 20")
